export const DEPARTMENT_SELECT_REQUEST = 'DEPARTMENT_SELECT_REQUEST';
export const DEPARTMENT_SELECT_SUCCESS = 'DEPARTMENT_SELECT_SUCCESS';
export const DEPARTMENT_SELECT_FAILURE = 'DEPARTMENT_SELECT_FAILURE';
